version: 1
disable_existing_loggers: false

formateadores:
  json:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter
  consola:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

manejadores:
  consola:
    class: logging.StreamHandler
    level: INFO
    formatter: consola
    stream: ext://sys.stdout
  
  archivo_json:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/migracion.log
    maxBytes: 10485760
    backupCount: 5

loggers:
  src:
    level: DEBUG
    handlers: [consola, archivo_json]
    propagate: false

root:
  level: INFO
  handlers: [consola, archivo_json]